[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60074",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60074/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60074/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60074/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60074",
    "id": 2599317410,
    "node_id": "I_kwDOAA0YD86a7m-i",
    "number": 60074,
    "title": "BUG: Pandas group by aggregate sum returning nan for a big dataset with mostly float64 values and a very few null values",
    "user": {
      "login": "ssdv1",
      "id": 160284219,
      "node_id": "U_kgDOCY2-Ow",
      "avatar_url": "https://avatars.githubusercontent.com/u/160284219?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ssdv1",
      "html_url": "https://github.com/ssdv1",
      "followers_url": "https://api.github.com/users/ssdv1/followers",
      "following_url": "https://api.github.com/users/ssdv1/following{/other_user}",
      "gists_url": "https://api.github.com/users/ssdv1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ssdv1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ssdv1/subscriptions",
      "organizations_url": "https://api.github.com/users/ssdv1/orgs",
      "repos_url": "https://api.github.com/users/ssdv1/repos",
      "events_url": "https://api.github.com/users/ssdv1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ssdv1/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-19T15:46:52Z",
    "updated_at": "2024-10-19T15:46:52Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nCode:\r\nneighborhood_stats = taxi_with_neighborhood.groupby('ntaname',dropna=True).agg({\r\n    'cost_per_mile': ['sum','count']\r\n}).reset_index()\r\n\r\nOutput:\r\nntaname\tcost_per_mile\r\nsum\tcount\r\n0\tAirport\tNaN\t470286\r\n1\tAllerton-Pelham Gardens\tNaN\t30\r\n2\tArden Heights\tNaN\t3\r\n3\tAstoria\tNaN\t28449\r\n4\tAuburndale\tNaN\t40\n```\n\n\n### Issue Description\n\n\r\n![Screenshot 2024-10-19 021337](https://github.com/user-attachments/assets/b887b073-24fa-438f-b719-b11adc6a5454)\r\n![Screenshot 2024-10-19 021405](https://github.com/user-attachments/assets/2a2b6206-ff8c-4ec3-b86a-1c14cdecfa66)\r\n`from azureml.opendatasets import NycTlcYellow\r\nfrom datetime import datetime\r\nfrom dateutil import parser\r\nimport geopandas as gpd\r\nfrom shapely.geometry import Point\r\nimport pandas as pd\r\n\r\nstart_date = parser.parse('2015-01-01')\r\nend_date = parser.parse('2015-01-31')\r\n\r\nnyc_tlc = NycTlcYellow(start_date=start_date, end_date=end_date)\r\ntaxi_data = nyc_tlc.to_pandas_dataframe()\r\n\r\ntaxi_data.info()\r\n\r\nneighborhoods = gpd.read_file('nyc/geo_export_efe01be6-5681-4d19-b441-eefd6f6bb3fa.shp')\r\n\r\ngeometry = [Point(xy) for xy in zip(taxi_data['startLon'], taxi_data['startLat'])]\r\ntaxi_gdf = gpd.GeoDataFrame(taxi_data, geometry=geometry, crs=\"EPSG:4326\")\r\n\r\ntaxi_with_neighborhood = gpd.sjoin(taxi_gdf, neighborhoods, how=\"left\", predicate=\"within\")\r\n\r\ntaxi_with_neighborhood['cost_per_mile'] = taxi_with_neighborhood['totalAmount'] / taxi_with_neighborhood['tripDistance']\r\n\r\ntaxi_with_neighborhood.reset_index(drop=True, inplace=True)\r\n\r\nneighborhood_stats = taxi_with_neighborhood.groupby('ntaname', dropna=True).agg({\r\n    'cost_per_mile': ['sum', 'count']\r\n}).reset_index()\r\n\r\nneighborhood_stats.head()\r\n\r\ntaxi_with_neighborhood['cost_per_mile'][0]\r\n\r\ncost_per_mile_sum = taxi_with_neighborhood.groupby('ntaname')['cost_per_mile'].sum()\r\n\r\nprint(cost_per_mile_sum)\r\n\r\ntaxi_with_neighborhood_pdf = pd.DataFrame(taxi_with_neighborhood)\r\n\r\nneighborhood_stats = taxi_with_neighborhood.groupby('ntaname', dropna=True).agg({\r\n    'cost_per_mile': ['sum', 'count']\r\n}).reset_index()\r\n\r\nneighborhood_stats.head()\r\n\r\npd.show_versions()\r\n`\n\n### Expected Behavior\n\nshould return float values for sum\n\n### Installed Versions\n\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 0f437949513225922d851e9581723d82120684a6\r\npython           : 3.10.15.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.10.0-32-cloud-amd64\r\nVersion          : #1 SMP Debian 5.10.223-1 (2024-08-10)\r\nmachine          : x86_64\r\nprocessor        : \r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : C.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 2.0.3\r\nnumpy            : 1.24.4\r\npytz             : 2024.2\r\ndateutil         : 2.9.0\r\nsetuptools       : 74.1.2\r\npip              : 24.2\r\nCython           : 3.0.11\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.1.4\r\nIPython          : 8.21.0\r\npandas_datareader: None\r\nbs4              : 4.12.3\r\nbottleneck       : None\r\nbrotli           : 1.1.0\r\nfastparquet      : None\r\nfsspec           : 2024.9.0\r\ngcsfs            : 2024.9.0post1\r\nmatplotlib       : 3.7.3\r\nnumba            : 0.58.1\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 9.0.0\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.11.4\r\nsnappy           : None\r\nsqlalchemy       : 2.0.35\r\ntables           : None\r\ntabulate         : 0.9.0\r\nxarray           : None\r\nxlrd             : None\r\nzstandard        : 0.23.0\r\ntzdata           : 2024.1\r\nqtpy             : None\r\npyqt5            : None\r\n\r\n</details>\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60074/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60074/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60073",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60073/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60073/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60073/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60073",
    "id": 2598379428,
    "node_id": "I_kwDOAA0YD86a4B-k",
    "number": 60073,
    "title": "BUG: ArrowDtype Series: Broadcasting Error with Single-Value Arrays in Arithmetic Operations",
    "user": {
      "login": "hombit",
      "id": 1784493,
      "node_id": "MDQ6VXNlcjE3ODQ0OTM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1784493?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hombit",
      "html_url": "https://github.com/hombit",
      "followers_url": "https://api.github.com/users/hombit/followers",
      "following_url": "https://api.github.com/users/hombit/following{/other_user}",
      "gists_url": "https://api.github.com/users/hombit/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hombit/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hombit/subscriptions",
      "organizations_url": "https://api.github.com/users/hombit/orgs",
      "repos_url": "https://api.github.com/users/hombit/repos",
      "events_url": "https://api.github.com/users/hombit/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hombit/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-18T20:57:49Z",
    "updated_at": "2024-10-18T20:58:22Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport numpy as np\r\nimport pandas as pd\r\nimport pyarrow as pa\r\n\r\nseries = pd.Series([1.0, 2.0, 3.0], dtype=pd.ArrowDtype(pa.float64()))\r\nseries / np.array([2.0])\r\n# ArrowInvalid: Array arguments must all be the same length\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nWhen performing arithmetic operations between a `Series` of `ArrowDtype` and a single-value array, the array is not broadcasted to match the series shape. Instead, it raises an `ArrowInvalid error`. This behavior is inconsistent, as the same operation works correctly with both default and numpy-nullable dtypes.\r\n\r\nA solution could be casting a single-element array to a `pa.Scalar` in `ArrowExtensionArray._evaluate_op_method`:\r\nhttps://github.com/pandas-dev/pandas/blob/2a10e04a099d5f1633abcdfbb2dd9fdf09142f8d/pandas/core/arrays/arrow/array.py#L755\r\n\r\n### Expected Behavior\r\n\r\nThe code doesn't fail, and behavior to be consistent over different dtype back-ends\r\n\r\n### Installed Versions\r\n\r\nPandas v2.2.3:\r\n\r\n<details>\r\n\r\n```\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\r\npython                : 3.12.7\r\npython-bits           : 64\r\nOS                    : Darwin\r\nOS-release            : 24.0.0\r\nVersion               : Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:36 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6020\r\nmachine               : arm64\r\nprocessor             : arm\r\nbyteorder             : little\r\nLC_ALL                : en_US.UTF-8\r\nLANG                  : en_US.UTF-8\r\nLOCALE                : en_US.UTF-8\r\npandas                : 2.2.3\r\nnumpy                 : 1.26.4\r\npytz                  : 2024.1\r\ndateutil              : 2.9.0.post0\r\npip                   : 24.2\r\nCython                : None\r\nsphinx                : 7.4.7\r\nIPython               : 8.26.0\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nblosc                 : None\r\nbottleneck            : None\r\ndataframe-api-compat  : None\r\nfastparquet           : None\r\nfsspec                : 2024.6.1\r\nhtml5lib              : None\r\nhypothesis            : None\r\ngcsfs                 : None\r\njinja2                : 3.1.4\r\nlxml.etree            : None\r\nmatplotlib            : 3.8.4\r\nnumba                 : 0.60.0\r\nnumexpr               : None\r\nodfpy                 : None\r\nopenpyxl              : None\r\npandas_gbq            : None\r\npsycopg2              : None\r\npymysql               : None\r\npyarrow               : 16.1.0\r\npyreadstat            : None\r\npytest                : 8.3.2\r\npython-calamine       : None\r\npyxlsb                : None\r\ns3fs                  : 2024.6.1\r\nscipy                 : 1.14.0\r\nsqlalchemy            : None\r\ntables                : None\r\ntabulate              : 0.9.0\r\nxarray                : None\r\nxlrd                  : None\r\nxlsxwriter            : None\r\nzstandard             : None\r\ntzdata                : 2024.1\r\nqtpy                  : None\r\npyqt5                 : None\r\n```\r\n\r\n</details>\r\n\r\nNightly Pandas:\r\n\r\n<details>\r\n\r\n```\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 2a10e04a099d5f1633abcdfbb2dd9fdf09142f8d\r\npython                : 3.12.7\r\npython-bits           : 64\r\nOS                    : Darwin\r\nOS-release            : 24.0.0\r\nVersion               : Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:36 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6020\r\nmachine               : arm64\r\nprocessor             : arm\r\nbyteorder             : little\r\nLC_ALL                : en_US.UTF-8\r\nLANG                  : en_US.UTF-8\r\nLOCALE                : en_US.UTF-8\r\n\r\npandas                : 3.0.0.dev0+1579.g2a10e04a09\r\nnumpy                 : 2.2.0.dev0+git20241015.961b70f\r\ndateutil              : 2.9.0.post0\r\npip                   : 24.2\r\nCython                : None\r\nsphinx                : None\r\nIPython               : 8.28.0\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : None\r\nblosc                 : None\r\nbottleneck            : None\r\nfastparquet           : None\r\nfsspec                : None\r\nhtml5lib              : None\r\nhypothesis            : None\r\ngcsfs                 : None\r\njinja2                : None\r\nlxml.etree            : None\r\nmatplotlib            : None\r\nnumba                 : None\r\nnumexpr               : None\r\nodfpy                 : None\r\nopenpyxl              : None\r\npsycopg2              : None\r\npymysql               : None\r\npyarrow               : 17.0.0\r\npyreadstat            : None\r\npytest                : None\r\npython-calamine       : None\r\npytz                  : None\r\npyxlsb                : None\r\ns3fs                  : None\r\nscipy                 : None\r\nsqlalchemy            : None\r\ntables                : None\r\ntabulate              : None\r\nxarray                : None\r\nxlrd                  : None\r\nxlsxwriter            : None\r\nzstandard             : None\r\ntzdata                : 2024.2\r\nqtpy                  : None\r\npyqt5                 : None\r\n```\r\n\r\n</details>",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60073/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60073/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60072",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60072/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60072/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60072/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60072",
    "id": 2598266275,
    "node_id": "PR_kwDOAA0YD85_I9AC",
    "number": 60072,
    "title": "DOC: fix SA01 for pandas.errors.UnsupportedFunctionCall",
    "user": {
      "login": "tuhinsharma121",
      "id": 6801780,
      "node_id": "MDQ6VXNlcjY4MDE3ODA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6801780?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuhinsharma121",
      "html_url": "https://github.com/tuhinsharma121",
      "followers_url": "https://api.github.com/users/tuhinsharma121/followers",
      "following_url": "https://api.github.com/users/tuhinsharma121/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuhinsharma121/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuhinsharma121/subscriptions",
      "organizations_url": "https://api.github.com/users/tuhinsharma121/orgs",
      "repos_url": "https://api.github.com/users/tuhinsharma121/repos",
      "events_url": "https://api.github.com/users/tuhinsharma121/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuhinsharma121/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-18T19:42:59Z",
    "updated_at": "2024-10-18T19:43:04Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60072",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60072",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60072.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60072.patch",
      "merged_at": null
    },
    "body": "fixes\r\n\r\n```\r\npandas.errors.UnsupportedFunctionCall SA01\r\n```",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60072/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60072/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60070",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60070/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60070/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60070/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60070",
    "id": 2598019717,
    "node_id": "I_kwDOAA0YD86a2qKF",
    "number": 60070,
    "title": "PERF: Extreme regression in 2.2 when aggregating a DataFrame with .attrs data",
    "user": {
      "login": "buhrmann",
      "id": 190342,
      "node_id": "MDQ6VXNlcjE5MDM0Mg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/190342?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/buhrmann",
      "html_url": "https://github.com/buhrmann",
      "followers_url": "https://api.github.com/users/buhrmann/followers",
      "following_url": "https://api.github.com/users/buhrmann/following{/other_user}",
      "gists_url": "https://api.github.com/users/buhrmann/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/buhrmann/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/buhrmann/subscriptions",
      "organizations_url": "https://api.github.com/users/buhrmann/orgs",
      "repos_url": "https://api.github.com/users/buhrmann/repos",
      "events_url": "https://api.github.com/users/buhrmann/events{/privacy}",
      "received_events_url": "https://api.github.com/users/buhrmann/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 8935311,
        "node_id": "MDU6TGFiZWw4OTM1MzEx",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Performance",
        "name": "Performance",
        "color": "a10c02",
        "default": false,
        "description": "Memory or execution speed performance"
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2024-10-18T17:14:01Z",
    "updated_at": "2024-10-18T18:08:50Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this issue exists on the main branch of pandas.\n\n\n### Reproducible Example\n\nHi, so it seems some interaction between copy-on-write and .attrs data leads to extremely slow performance, at least with custom aggregations. In the below code, the timed aggregations all perform identical in v2.1. But in v2.2, the last one, with custom .attrs data and copy-on-write enabled, is about 10x slower. Using my original dataset, which I cannot share, but which is simply larger in both dimensions, the result was even more extreme, being almost 50x slower (from less than a second to 40s).\r\n\r\n``` python\r\nimport numpy as np\r\nimport pandas as pd\r\nfrom sklearn import datasets\r\nfrom pandas import options as pdopt\r\n\r\nprint(f\"{pd.__version__=}\")\r\n\r\nX, y = datasets.fetch_covtype(return_X_y=True, as_frame=True)\r\nX[\"group\"] = np.random.choice(range(20_000), size=len(X))\r\n\r\nprint(\"\\nExecution times with and without metadata before setting copy_on_write to 'warn'\")\r\n%timeit -n1 -r1 X.groupby(\"group\").Elevation.apply(lambda ser: (ser >= 3000).sum() / len(ser))\r\nX.attrs[\"metadata\"] = {col: {\"hello\": {\"world\": \"foobar\"}} for col in X.columns}\r\n%timeit -n1 -r1 X.groupby(\"group\").Elevation.apply(lambda ser: (ser >= 3000).sum() / len(ser))\r\n\r\npdopt.mode.copy_on_write = True #\"warn\"\r\n\r\nX, y = datasets.fetch_covtype(return_X_y=True, as_frame=True)\r\nX[\"group\"] = np.random.choice(range(20_000), size=len(X))\r\n\r\nprint(\"\\nExecution times with and without metadata after setting copy_on_write to 'warn'\")\r\n%timeit -n1 -r1 X.groupby(\"group\").Elevation.apply(lambda ser: (ser >= 3000).sum() / len(ser))\r\nX.attrs[\"metadata\"] = {col: {\"hello\": {\"world\": \"foobar\"}} for col in X.columns}\r\n%timeit -n1 -r1 X.groupby(\"group\").Elevation.apply(lambda ser: (ser >= 3000).sum() / len(ser))\r\n```\r\n\r\nThe output:\r\n```\r\npd.__version__='2.2.3'\r\n\r\nExecution times with and without metadata before setting copy_on_write to 'warn'\r\n661 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)\r\n667 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)\r\n\r\nExecution times with and without metadata after setting copy_on_write to 'warn'\r\n671 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)\r\n5.22 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)\r\n```\n\n### Installed Versions\n\n<details>\r\n\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\r\npython                : 3.10.15\r\npython-bits           : 64\r\nOS                    : Darwin\r\nOS-release            : 24.0.0\r\nVersion               : Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:26 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8103\r\nmachine               : arm64\r\nprocessor             : arm\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : None\r\nLOCALE                : None.UTF-8\r\n\r\npandas                : 2.2.3\r\nnumpy                 : 1.26.4\r\npytz                  : 2024.1\r\ndateutil              : 2.9.0\r\npip                   : 24.2\r\nCython                : 0.29.37\r\nsphinx                : 8.1.3\r\nIPython               : 8.28.0\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nblosc                 : None\r\nbottleneck            : None\r\ndataframe-api-compat  : None\r\nfastparquet           : None\r\nfsspec                : 2024.9.0\r\nhtml5lib              : None\r\nhypothesis            : None\r\ngcsfs                 : None\r\njinja2                : 3.1.4\r\nlxml.etree            : 5.3.0\r\nmatplotlib            : 3.9.2\r\nnumba                 : 0.60.0\r\nnumexpr               : None\r\nodfpy                 : None\r\nopenpyxl              : 3.1.5\r\npandas_gbq            : 0.23.0\r\npsycopg2              : 2.9.10\r\npymysql               : 1.4.6\r\npyarrow               : 16.1.0\r\npyreadstat            : 1.2.7\r\npytest                : 8.3.3\r\npython-calamine       : None\r\npyxlsb                : None\r\ns3fs                  : None\r\nscipy                 : 1.11.3\r\nsqlalchemy            : 2.0.36\r\ntables                : None\r\ntabulate              : None\r\nxarray                : None\r\nxlrd                  : 2.0.1\r\nxlsxwriter            : None\r\nzstandard             : 0.23.0\r\ntzdata                : 2024.2\r\nqtpy                  : None\r\npyqt5                 : None\r\n\r\n</details>\r\n\n\n### Prior Performance\n\n```\r\npd.__version__='2.1.4'\r\n\r\nExecution times with and without metadata before setting copy_on_write to 'warn'\r\n703 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)\r\n695 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)\r\n\r\nExecution times with and without metadata after setting copy_on_write to 'warn'\r\n694 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)\r\n691 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)\r\n```",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60070/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60070/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60069",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60069/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60069/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60069/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60069",
    "id": 2597932252,
    "node_id": "PR_kwDOAA0YD85_H9qe",
    "number": 60069,
    "title": "Delete exception from pandas frame",
    "user": {
      "login": "venikkus",
      "id": 74638771,
      "node_id": "MDQ6VXNlcjc0NjM4Nzcx",
      "avatar_url": "https://avatars.githubusercontent.com/u/74638771?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/venikkus",
      "html_url": "https://github.com/venikkus",
      "followers_url": "https://api.github.com/users/venikkus/followers",
      "following_url": "https://api.github.com/users/venikkus/following{/other_user}",
      "gists_url": "https://api.github.com/users/venikkus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/venikkus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/venikkus/subscriptions",
      "organizations_url": "https://api.github.com/users/venikkus/orgs",
      "repos_url": "https://api.github.com/users/venikkus/repos",
      "events_url": "https://api.github.com/users/venikkus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/venikkus/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-18T16:20:46Z",
    "updated_at": "2024-10-18T16:20:46Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60069",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60069",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60069.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60069.patch",
      "merged_at": null
    },
    "body": "- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60069/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60069/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60068",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60068/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60068/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60068/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60068",
    "id": 2597515288,
    "node_id": "I_kwDOAA0YD86a0vAY",
    "number": 60068,
    "title": "BUG: Failures with ArrowDtype(pa.string_view())",
    "user": {
      "login": "a10y",
      "id": 332583,
      "node_id": "MDQ6VXNlcjMzMjU4Mw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/332583?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/a10y",
      "html_url": "https://github.com/a10y",
      "followers_url": "https://api.github.com/users/a10y/followers",
      "following_url": "https://api.github.com/users/a10y/following{/other_user}",
      "gists_url": "https://api.github.com/users/a10y/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/a10y/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/a10y/subscriptions",
      "organizations_url": "https://api.github.com/users/a10y/orgs",
      "repos_url": "https://api.github.com/users/a10y/repos",
      "events_url": "https://api.github.com/users/a10y/events{/privacy}",
      "received_events_url": "https://api.github.com/users/a10y/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2024-10-18T13:24:34Z",
    "updated_at": "2024-10-18T13:32:51Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd # pandas 2.2.3 => latest\r\nimport pyarrow as pa # pyarrow 17.0.0 => latest\r\n\r\ntab = pa.table({\"names\": pa.array([\"a\", \"b\", \"c\"], type=pa.string_view())})\r\n\r\n# this succeeds\r\ntab.to_pandas()\r\n\r\n# this throws an exception\r\ntab.to_pandas(types_mapper=pd.ArrowDtype)\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nOur library is producing Arrow binary view arrays (strings and binary) and we want to allow users to convert into Pandas DataFrame.\r\n\r\nWe are using the `pd.ArrowDtype` constructor to allow creating Pandas arrays that are backed with Arrow storage. The example I've attached fails also when you change `\"c\"` to `None` (i.e. problem hits for both nullable and non-nullable types).\r\n\r\nFull repro with error message:\r\n\r\n```\r\n>>> import pandas as pd # pandas 2.2.3 => latest\r\n>>> import pyarrow as pa # pyarrow 17.0.0 => latest\r\n>>>\r\n>>> tab = pa.table({\"names\": pa.array([\"a\", \"b\", \"c\"], type=pa.string_view())})\r\n>>>\r\n>>> # this succeeds\r\n>>> tab.to_pandas()\r\n  names\r\n0     a\r\n1     b\r\n2     c\r\n>>>\r\n>>> # this throws an exception\r\n>>> tab.to_pandas(types_mapper=pd.ArrowDtype)\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/core/frame.py\", line 1214, in __repr__\r\n    return self.to_string(**repr_params)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/util/_decorators.py\", line 333, in wrapper\r\n    return func(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/core/frame.py\", line 1394, in to_string\r\n    return fmt.DataFrameRenderer(formatter).to_string(\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/io/formats/format.py\", line 962, in to_string\r\n    string = string_formatter.to_string()\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/io/formats/string.py\", line 29, in to_string\r\n    text = self._get_string_representation()\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/io/formats/string.py\", line 44, in _get_string_representation\r\n    strcols = self._get_strcols()\r\n              ^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/io/formats/string.py\", line 35, in _get_strcols\r\n    strcols = self.fmt.get_strcols()\r\n              ^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/io/formats/format.py\", line 476, in get_strcols\r\n    strcols = self._get_strcols_without_index()\r\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/io/formats/format.py\", line 729, in _get_strcols_without_index\r\n    str_columns = self._get_formatted_column_labels(self.tr_frame)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/io/formats/format.py\", line 809, in _get_formatted_column_labels\r\n    need_leadsp = dict(zip(fmt_columns, map(is_numeric_dtype, dtypes)))\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/core/dtypes/common.py\", line 1119, in is_numeric_dtype\r\n    return _is_dtype_type(\r\n           ^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/core/dtypes/common.py\", line 1468, in _is_dtype_type\r\n    tipo = pandas_dtype(arr_or_dtype).type\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Volumes/Code/vortex/.venv/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py\", line 2169, in type\r\n    raise NotImplementedError(pa_type)\r\nNotImplementedError: string_view\r\n>>>\r\n```\r\n\r\nThis seems like a distinct issue from #59883. \r\n\r\n### Expected Behavior\r\n\r\nI'd expect the throwing example to not throw.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\n**Device:** macOS 14.4.1 M2 Max MBP\r\n\r\n```\r\n>>> pd.show_versions()\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\r\npython                : 3.11.9\r\npython-bits           : 64\r\nOS                    : Darwin\r\nOS-release            : 23.4.0\r\nVersion               : Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020\r\nmachine               : arm64\r\nprocessor             : arm\r\nbyteorder             : little\r\nLC_ALL                : en_US.UTF-8\r\nLANG                  : None\r\nLOCALE                : en_US.UTF-8\r\n\r\npandas                : 2.2.3\r\nnumpy                 : 1.26.4\r\npytz                  : 2024.1\r\ndateutil              : 2.9.0.post0\r\npip                   : 24.0\r\nCython                : None\r\nsphinx                : 8.0.2\r\nIPython               : 8.26.0\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nblosc                 : None\r\nbottleneck            : None\r\ndataframe-api-compat  : None\r\nfastparquet           : None\r\nfsspec                : None\r\nhtml5lib              : None\r\nhypothesis            : None\r\ngcsfs                 : None\r\njinja2                : 3.1.3\r\nlxml.etree            : None\r\nmatplotlib            : 3.9.2\r\nnumba                 : None\r\nnumexpr               : None\r\nodfpy                 : None\r\nopenpyxl              : None\r\npandas_gbq            : None\r\npsycopg2              : None\r\npymysql               : None\r\npyarrow               : 17.0.0\r\npyreadstat            : None\r\npytest                : 8.1.1\r\npython-calamine       : None\r\npyxlsb                : None\r\ns3fs                  : None\r\nscipy                 : None\r\nsqlalchemy            : None\r\ntables                : None\r\ntabulate              : None\r\nxarray                : 2024.7.0\r\nxlrd                  : None\r\nxlsxwriter            : None\r\nzstandard             : None\r\ntzdata                : 2024.1\r\nqtpy                  : None\r\npyqt5                 : None\r\n\r\n```\r\n\r\n</details>\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60068/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60068/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60067",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60067/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60067/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60067/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60067",
    "id": 2596954088,
    "node_id": "PR_kwDOAA0YD85_E4_g",
    "number": 60067,
    "title": "Testing ",
    "user": {
      "login": "Saumya0206",
      "id": 60199756,
      "node_id": "MDQ6VXNlcjYwMTk5NzU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/60199756?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Saumya0206",
      "html_url": "https://github.com/Saumya0206",
      "followers_url": "https://api.github.com/users/Saumya0206/followers",
      "following_url": "https://api.github.com/users/Saumya0206/following{/other_user}",
      "gists_url": "https://api.github.com/users/Saumya0206/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Saumya0206/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Saumya0206/subscriptions",
      "organizations_url": "https://api.github.com/users/Saumya0206/orgs",
      "repos_url": "https://api.github.com/users/Saumya0206/repos",
      "events_url": "https://api.github.com/users/Saumya0206/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Saumya0206/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-18T09:18:45Z",
    "updated_at": "2024-10-18T10:29:27Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60067",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60067",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60067.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60067.patch",
      "merged_at": null
    },
    "body": "- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60067/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60067/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60066",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60066/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60066/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60066/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60066",
    "id": 2596277883,
    "node_id": "I_kwDOAA0YD86awA57",
    "number": 60066,
    "title": "PERF: df.astype(\"float64[pyarrow]\") is slow, df.astype(\"Float64\") is super slow",
    "user": {
      "login": "auderson",
      "id": 48577571,
      "node_id": "MDQ6VXNlcjQ4NTc3NTcx",
      "avatar_url": "https://avatars.githubusercontent.com/u/48577571?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/auderson",
      "html_url": "https://github.com/auderson",
      "followers_url": "https://api.github.com/users/auderson/followers",
      "following_url": "https://api.github.com/users/auderson/following{/other_user}",
      "gists_url": "https://api.github.com/users/auderson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/auderson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/auderson/subscriptions",
      "organizations_url": "https://api.github.com/users/auderson/orgs",
      "repos_url": "https://api.github.com/users/auderson/repos",
      "events_url": "https://api.github.com/users/auderson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/auderson/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 8935311,
        "node_id": "MDU6TGFiZWw4OTM1MzEx",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Performance",
        "name": "Performance",
        "color": "a10c02",
        "default": false,
        "description": "Memory or execution speed performance"
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-18T03:03:51Z",
    "updated_at": "2024-10-18T03:03:51Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this issue exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\r\nimport pandas as pd\r\nimport numpy as np\r\n\r\ndf = pd.DataFrame(np.zeros((5000, 5000)))\r\n```\r\n```python\r\n%%time\r\n_ = df.astype(\"Float64\")\r\n```\r\nCPU times: user 3.87 s, sys: 185 ms, total: 4.05 s\r\nWall time: 4.05 s\r\n\r\n```python\r\n%%timeit\r\n_ = df.astype(\"float64[pyarrow]\")\r\n```\r\n566 ms ± 15.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)\r\n\r\n```python\r\n%%timeit\r\n_ = df.astype(\"float64\", copy=True)\r\n```\r\n148 ms ± 984 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)\r\n\r\nIt takes over 4s for a middle-sized dataframe of 5000 x 5000 to convert to `Float64`, while `float64[pyarrow]` is about 7x faster. The fastest `float64` takes only 150ms, even with `copy` enabled.\n\n### Installed Versions\n\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\r\npython                : 3.10.14\r\npython-bits           : 64\r\nOS                    : Linux\r\nOS-release            : 5.15.0-122-generic\r\nVersion               : #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024\r\nmachine               : x86_64\r\nprocessor             : x86_64\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : en_US.UTF-8\r\nLOCALE                : en_US.UTF-8\r\n\r\npandas                : 2.2.3\r\nnumpy                 : 1.26.4\r\npytz                  : 2024.1\r\ndateutil              : 2.9.0\r\npip                   : 24.0\r\nCython                : 3.0.7\r\nsphinx                : 7.3.7\r\nIPython               : 8.25.0\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nblosc                 : None\r\nbottleneck            : None\r\ndataframe-api-compat  : None\r\nfastparquet           : None\r\nfsspec                : 2024.6.0\r\nhtml5lib              : None\r\nhypothesis            : None\r\ngcsfs                 : None\r\njinja2                : 3.1.4\r\nlxml.etree            : None\r\nmatplotlib            : 3.9.2\r\nnumba                 : 0.60.0\r\nnumexpr               : 2.10.0\r\nodfpy                 : None\r\nopenpyxl              : None\r\npandas_gbq            : None\r\npsycopg2              : 2.9.9\r\npymysql               : 1.4.6\r\npyarrow               : 16.1.0\r\npyreadstat            : None\r\npytest                : 8.2.2\r\npython-calamine       : None\r\npyxlsb                : None\r\ns3fs                  : None\r\nscipy                 : 1.14.0\r\nsqlalchemy            : 2.0.31\r\ntables                : 3.9.2\r\ntabulate              : None\r\nxarray                : None\r\nxlrd                  : None\r\nxlsxwriter            : None\r\nzstandard             : 0.22.0\r\ntzdata                : 2024.1\r\nqtpy                  : 2.4.1\r\npyqt5                 : None\r\n</details>\r\n\n\n### Prior Performance\n\n_No response_",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60066/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60066/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60065",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60065/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60065/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60065/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60065",
    "id": 2595494947,
    "node_id": "I_kwDOAA0YD86atBwj",
    "number": 60065,
    "title": "BUG: `str.split(\"\")` gives extra leading and trailing elements",
    "user": {
      "login": "NickCrews",
      "id": 10820686,
      "node_id": "MDQ6VXNlcjEwODIwNjg2",
      "avatar_url": "https://avatars.githubusercontent.com/u/10820686?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/NickCrews",
      "html_url": "https://github.com/NickCrews",
      "followers_url": "https://api.github.com/users/NickCrews/followers",
      "following_url": "https://api.github.com/users/NickCrews/following{/other_user}",
      "gists_url": "https://api.github.com/users/NickCrews/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/NickCrews/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/NickCrews/subscriptions",
      "organizations_url": "https://api.github.com/users/NickCrews/orgs",
      "repos_url": "https://api.github.com/users/NickCrews/repos",
      "events_url": "https://api.github.com/users/NickCrews/events{/privacy}",
      "received_events_url": "https://api.github.com/users/NickCrews/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2024-10-17T18:53:02Z",
    "updated_at": "2024-10-18T16:27:43Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\n\r\nvals = [\"foo\", \"\", None]\r\npd.Series(vals).str.split(\"\").tolist()\r\n# actual: [['', 'f', 'o', 'o', ''], ['', ''], None]\r\n# expected option A, see below: [['f', 'o', 'o'], [], None]\r\n# expected option B, see below: [['f', 'o', 'o'], [''], None]\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nWhile I think the current behavior is definitely wrong, I'm not sure if expected behavior should be A or B from above. Here is a brief survey of what peers do:\r\n- Using vanilla python, eg `\"foo\".split(\"\")`, gives an error (I should use `list(\"foo\")` instead)\r\n- In duckdb, `STR_SPLIT(vals, '')` gives `[['f', 'o', 'o'], [''], None]`\r\n- in polars, `vals.str.split(\"\")` gives `[['f', 'o', 'o'], [], None]`\r\n\r\nSee https://github.com/duckdb/duckdb/issues/14414 for a discussion of pros and cons of both.\r\n\r\n\r\n\r\n### Expected Behavior\r\n\r\nIn the above linked duckdb issue I argue for why behavior A I think is best.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\r\npython                : 3.11.6\r\npython-bits           : 64\r\nOS                    : Darwin\r\nOS-release            : 23.6.0\r\nVersion               : Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000\r\nmachine               : arm64\r\nprocessor             : arm\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : None\r\nLOCALE                : None.UTF-8\r\n\r\npandas                : 2.2.3\r\nnumpy                 : 2.1.2\r\npytz                  : 2024.2\r\ndateutil              : 2.9.0.post0\r\npip                   : 23.2.1\r\nCython                : None\r\nsphinx                : None\r\nIPython               : 8.28.0\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nblosc                 : None\r\nbottleneck            : None\r\ndataframe-api-compat  : None\r\nfastparquet           : None\r\nfsspec                : 2024.9.0\r\nhtml5lib              : None\r\nhypothesis            : 6.115.0\r\ngcsfs                 : 2024.9.0post1\r\njinja2                : 3.1.4\r\nlxml.etree            : None\r\nmatplotlib            : 3.9.2\r\nnumba                 : None\r\nnumexpr               : None\r\nodfpy                 : None\r\nopenpyxl              : None\r\npandas_gbq            : None\r\npsycopg2              : 2.9.9\r\npymysql               : 1.4.6\r\npyarrow               : 17.0.0\r\npyreadstat            : None\r\npytest                : 8.3.3\r\npython-calamine       : None\r\npyxlsb                : None\r\ns3fs                  : None\r\nscipy                 : 1.14.1\r\nsqlalchemy            : 2.0.35\r\ntables                : None\r\ntabulate              : 0.9.0\r\nxarray                : None\r\nxlrd                  : None\r\nxlsxwriter            : None\r\nzstandard             : 0.23.0\r\ntzdata                : 2024.2\r\nqtpy                  : None\r\npyqt5                 : None\r\n\r\n</details>\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60065/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60065/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60064",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60064/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60064/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60064/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60064",
    "id": 2595292260,
    "node_id": "I_kwDOAA0YD86asQRk",
    "number": 60064,
    "title": "BUG: DataFrame(data=[None, 1], dtype='timedelta64[ns]') raises ValueError: Buffer has wrong number of dimensions",
    "user": {
      "login": "sfc-gh-mvashishtha",
      "id": 149194323,
      "node_id": "U_kgDOCOSGUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/149194323?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sfc-gh-mvashishtha",
      "html_url": "https://github.com/sfc-gh-mvashishtha",
      "followers_url": "https://api.github.com/users/sfc-gh-mvashishtha/followers",
      "following_url": "https://api.github.com/users/sfc-gh-mvashishtha/following{/other_user}",
      "gists_url": "https://api.github.com/users/sfc-gh-mvashishtha/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sfc-gh-mvashishtha/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sfc-gh-mvashishtha/subscriptions",
      "organizations_url": "https://api.github.com/users/sfc-gh-mvashishtha/orgs",
      "repos_url": "https://api.github.com/users/sfc-gh-mvashishtha/repos",
      "events_url": "https://api.github.com/users/sfc-gh-mvashishtha/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sfc-gh-mvashishtha/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-17T17:10:59Z",
    "updated_at": "2024-10-17T17:10:59Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\ndf = pd.DataFrame([None, 1], dtype='timedelta64[ns]')\n```\n\n\n### Issue Description\n\nThe error message doesn't tell the user what to do differently. Also, it's possible that there shouldn't be an error at all.\n\n### Expected Behavior\n\nI think this should be allowed, in which case the resulting series would look like\r\n\r\n```\r\n                          0\r\n0                       NaT\r\n1 0 days 00:00:00.000000001\r\n```\r\n\r\nIf it's not allowed, the error message should be clearer.\n\n### Installed Versions\n\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\r\npython                : 3.9.18\r\npython-bits           : 64\r\nOS                    : Darwin\r\nOS-release            : 23.6.0\r\nVersion               : Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:52 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6020\r\nmachine               : arm64\r\nprocessor             : arm\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : en_US.UTF-8\r\nLOCALE                : en_US.UTF-8\r\n\r\npandas                : 2.2.3\r\nnumpy                 : 1.26.3\r\npytz                  : 2023.3.post1\r\ndateutil              : 2.8.2\r\npip                   : 23.3.1\r\nCython                : None\r\nsphinx                : None\r\nIPython               : 8.18.1\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : None\r\nblosc                 : None\r\nbottleneck            : None\r\ndataframe-api-compat  : None\r\nfastparquet           : None\r\nfsspec                : None\r\nhtml5lib              : None\r\nhypothesis            : None\r\ngcsfs                 : None\r\njinja2                : None\r\nlxml.etree            : None\r\nmatplotlib            : None\r\nnumba                 : None\r\nnumexpr               : None\r\nodfpy                 : None\r\nopenpyxl              : None\r\npandas_gbq            : None\r\npsycopg2              : None\r\npymysql               : None\r\npyarrow               : None\r\npyreadstat            : None\r\npytest                : 8.3.2\r\npython-calamine       : None\r\npyxlsb                : None\r\ns3fs                  : None\r\nscipy                 : None\r\nsqlalchemy            : None\r\ntables                : None\r\ntabulate              : None\r\nxarray                : None\r\nxlrd                  : None\r\nxlsxwriter            : None\r\nzstandard             : None\r\ntzdata                : 2023.4\r\nqtpy                  : None\r\npyqt5                 : None\r\n\r\n</details>\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60064/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60064/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60063",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60063/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60063/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60063/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60063",
    "id": 2594182177,
    "node_id": "I_kwDOAA0YD86aoBQh",
    "number": 60063,
    "title": "BUG: `to_latex()` does not handle braces in new headers gracefully",
    "user": {
      "login": "GregersSR",
      "id": 1908985,
      "node_id": "MDQ6VXNlcjE5MDg5ODU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1908985?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GregersSR",
      "html_url": "https://github.com/GregersSR",
      "followers_url": "https://api.github.com/users/GregersSR/followers",
      "following_url": "https://api.github.com/users/GregersSR/following{/other_user}",
      "gists_url": "https://api.github.com/users/GregersSR/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GregersSR/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GregersSR/subscriptions",
      "organizations_url": "https://api.github.com/users/GregersSR/orgs",
      "repos_url": "https://api.github.com/users/GregersSR/repos",
      "events_url": "https://api.github.com/users/GregersSR/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GregersSR/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-10-17T09:39:26Z",
    "updated_at": "2024-10-17T09:41:14Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\n\r\ndf = pd.DataFrame({\"a\": [1, 2]})\r\nresult = df.to_latex(header=[r\"$\\bar{y}$\"])\n```\n\n\n### Issue Description\n\nThis gives a `KeyError`. I looked into the reason, and it happens because at some point `r\"$\\bar{y}$\".format(x)` is called, and the braces are interpreted as string interpolation.\n\n### Expected Behavior\n\nI expect one of the following:\r\n1. An error message saying that single braces should be escaped using `{{`\r\n2. Documentation stating the same thing\r\n3. That the single brace is not interpreted as string interpolation\n\n### Installed Versions\n\n<details>\r\n\r\n>>> pd.show_versions()\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 2a10e04a099d5f1633abcdfbb2dd9fdf09142f8d\r\npython                : 3.10.15\r\npython-bits           : 64\r\nOS                    : Linux\r\nOS-release            : 6.8.0-45-generic\r\nVersion               : #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024\r\nmachine               : x86_64\r\nprocessor             : x86_64\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : en_US.UTF-8\r\nLOCALE                : en_US.UTF-8\r\n\r\npandas                : 3.0.0.dev0+1579.g2a10e04a09\r\nnumpy                 : 1.26.4\r\ndateutil              : 2.9.0\r\npip                   : 24.2\r\nCython                : 3.0.11\r\nsphinx                : 8.1.3\r\nIPython               : 8.28.0\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nblosc                 : None\r\nbottleneck            : 1.4.1\r\nfastparquet           : 2024.5.0\r\nfsspec                : 2024.9.0\r\nhtml5lib              : 1.1\r\nhypothesis            : 6.115.2\r\ngcsfs                 : 2024.9.0post1\r\njinja2                : 3.1.4\r\nlxml.etree            : 5.3.0\r\nmatplotlib            : 3.9.2\r\nnumba                 : 0.60.0\r\nnumexpr               : 2.10.1\r\nodfpy                 : None\r\nopenpyxl              : 3.1.5\r\npsycopg2              : 2.9.9\r\npymysql               : 1.4.6\r\npyarrow               : 17.0.0\r\npyreadstat            : 1.2.7\r\npytest                : 8.3.3\r\npython-calamine       : None\r\npytz                  : 2024.2\r\npyxlsb                : 1.0.10\r\ns3fs                  : 2024.9.0\r\nscipy                 : 1.14.1\r\nsqlalchemy            : 2.0.36\r\ntables                : 3.10.1\r\ntabulate              : 0.9.0\r\nxarray                : 2024.9.0\r\nxlrd                  : 2.0.1\r\nxlsxwriter            : 3.2.0\r\nzstandard             : 0.23.0\r\ntzdata                : 2024.2\r\nqtpy                  : None\r\npyqt5                 : None\r\n\r\n\r\n</details>\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60063/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60063/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60061",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60061/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60061/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60061/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60061",
    "id": 2593733468,
    "node_id": "PR_kwDOAA0YD85-65f4",
    "number": 60061,
    "title": "DOC: fix SA01 for pandas.errors.PossiblePrecisionLoss",
    "user": {
      "login": "tuhinsharma121",
      "id": 6801780,
      "node_id": "MDQ6VXNlcjY4MDE3ODA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6801780?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuhinsharma121",
      "html_url": "https://github.com/tuhinsharma121",
      "followers_url": "https://api.github.com/users/tuhinsharma121/followers",
      "following_url": "https://api.github.com/users/tuhinsharma121/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuhinsharma121/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuhinsharma121/subscriptions",
      "organizations_url": "https://api.github.com/users/tuhinsharma121/orgs",
      "repos_url": "https://api.github.com/users/tuhinsharma121/repos",
      "events_url": "https://api.github.com/users/tuhinsharma121/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuhinsharma121/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-17T06:18:04Z",
    "updated_at": "2024-10-17T08:17:13Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60061",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60061",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60061.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60061.patch",
      "merged_at": null
    },
    "body": "fixes\r\n\r\n```\r\npandas.errors.PossiblePrecisionLoss SA01\r\n```",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60061/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60061/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60060",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60060/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60060/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60060/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60060",
    "id": 2592691758,
    "node_id": "PR_kwDOAA0YD85-3vd-",
    "number": 60060,
    "title": "DOC: fix SA01,ES01 for pandas.tseries.offsets.SemiMonthBegin",
    "user": {
      "login": "tuhinsharma121",
      "id": 6801780,
      "node_id": "MDQ6VXNlcjY4MDE3ODA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6801780?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuhinsharma121",
      "html_url": "https://github.com/tuhinsharma121",
      "followers_url": "https://api.github.com/users/tuhinsharma121/followers",
      "following_url": "https://api.github.com/users/tuhinsharma121/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuhinsharma121/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuhinsharma121/subscriptions",
      "organizations_url": "https://api.github.com/users/tuhinsharma121/orgs",
      "repos_url": "https://api.github.com/users/tuhinsharma121/repos",
      "events_url": "https://api.github.com/users/tuhinsharma121/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuhinsharma121/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-16T18:19:08Z",
    "updated_at": "2024-10-17T05:53:32Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60060",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60060",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60060.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60060.patch",
      "merged_at": null
    },
    "body": "fixes\r\n\r\n```\r\npandas.tseries.offsets.SemiMonthBegin SA01, ES01\r\n```",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60060/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60060/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60059",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60059/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60059/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60059/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60059",
    "id": 2591956636,
    "node_id": "I_kwDOAA0YD86afh6c",
    "number": 60059,
    "title": "QST: Will pandas 3 support python 3.10?",
    "user": {
      "login": "wirable23",
      "id": 130208769,
      "node_id": "U_kgDOB8LUAQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/130208769?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wirable23",
      "html_url": "https://github.com/wirable23",
      "followers_url": "https://api.github.com/users/wirable23/followers",
      "following_url": "https://api.github.com/users/wirable23/following{/other_user}",
      "gists_url": "https://api.github.com/users/wirable23/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wirable23/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wirable23/subscriptions",
      "organizations_url": "https://api.github.com/users/wirable23/orgs",
      "repos_url": "https://api.github.com/users/wirable23/repos",
      "events_url": "https://api.github.com/users/wirable23/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wirable23/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 34444536,
        "node_id": "MDU6TGFiZWwzNDQ0NDUzNg==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question",
        "name": "Usage Question",
        "color": "0052cc",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-16T13:47:54Z",
    "updated_at": "2024-10-16T13:47:54Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Research\n\n- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.\n\n- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).\n\n\n### Link to question on StackOverflow\n\nNA\n\n### Question about pandas\n\nPer spec0, python 3.10 support should be dropped. Will pandas 3 still support it?",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60059/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60059/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60058",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60058/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60058/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60058/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60058",
    "id": 2591730568,
    "node_id": "PR_kwDOAA0YD85-0osq",
    "number": 60058,
    "title": "DOC: Solution for issue #60044",
    "user": {
      "login": "ZKaoChi",
      "id": 171681959,
      "node_id": "U_kgDOCjuopw",
      "avatar_url": "https://avatars.githubusercontent.com/u/171681959?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ZKaoChi",
      "html_url": "https://github.com/ZKaoChi",
      "followers_url": "https://api.github.com/users/ZKaoChi/followers",
      "following_url": "https://api.github.com/users/ZKaoChi/following{/other_user}",
      "gists_url": "https://api.github.com/users/ZKaoChi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ZKaoChi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ZKaoChi/subscriptions",
      "organizations_url": "https://api.github.com/users/ZKaoChi/orgs",
      "repos_url": "https://api.github.com/users/ZKaoChi/repos",
      "events_url": "https://api.github.com/users/ZKaoChi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ZKaoChi/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2024-10-16T12:23:38Z",
    "updated_at": "2024-10-17T07:57:05Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60058",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60058",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60058.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60058.patch",
      "merged_at": null
    },
    "body": "- [ ] closes #60044 \r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60058/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60058/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60056",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60056/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60056/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60056/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60056",
    "id": 2591111766,
    "node_id": "PR_kwDOAA0YD85-yr5M",
    "number": 60056,
    "title": "DOC: fixed docstring of timedelta.ceil to match docstring of datetimeindex…",
    "user": {
      "login": "Swati-Sneha",
      "id": 16612983,
      "node_id": "MDQ6VXNlcjE2NjEyOTgz",
      "avatar_url": "https://avatars.githubusercontent.com/u/16612983?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Swati-Sneha",
      "html_url": "https://github.com/Swati-Sneha",
      "followers_url": "https://api.github.com/users/Swati-Sneha/followers",
      "following_url": "https://api.github.com/users/Swati-Sneha/following{/other_user}",
      "gists_url": "https://api.github.com/users/Swati-Sneha/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Swati-Sneha/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Swati-Sneha/subscriptions",
      "organizations_url": "https://api.github.com/users/Swati-Sneha/orgs",
      "repos_url": "https://api.github.com/users/Swati-Sneha/repos",
      "events_url": "https://api.github.com/users/Swati-Sneha/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Swati-Sneha/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-16T08:42:06Z",
    "updated_at": "2024-10-16T08:42:06Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60056",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60056",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60056.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60056.patch",
      "merged_at": null
    },
    "body": "This PR fixes the document for pandas Timedelta.ceil.\r\n\r\nIt also adds summary to pandas Timedelta.ceil, Timedelta.floor and Timedelta.round to pass the [docstring validation](https://pandas.pydata.org/docs/dev/development/contributing_documentation.html#updating-a-pandas-docstring)\r\n\r\n- [x] closes #59902 (Replace xxxx with the GitHub issue number)\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n\r\n\r\nAttaching screenshots for changes, tested in local:\r\n<img width=\"1421\" alt=\"Screenshot 2024-10-16 at 14 02 45\" src=\"https://github.com/user-attachments/assets/e4ae20a7-4ee7-462f-b47a-2fcb6416f450\">\r\n<img width=\"1409\" alt=\"Screenshot 2024-10-16 at 12 48 42\" src=\"https://github.com/user-attachments/assets/68af401d-6b6b-4f12-bd7a-fdb0d129aeec\">\r\n<img width=\"1403\" alt=\"Screenshot 2024-10-16 at 12 48 52\" src=\"https://github.com/user-attachments/assets/c8219cb0-a7ea-47f1-9d1f-acc8f76d1b57\">\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60056/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60056/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60054",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60054/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60054/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60054/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60054",
    "id": 2590666177,
    "node_id": "PR_kwDOAA0YD85-xSOb",
    "number": 60054,
    "title": "Fix Date Parsing Issue in Arrow Parser for CSV Files (#59904)",
    "user": {
      "login": "Lavishgangwani",
      "id": 154001570,
      "node_id": "U_kgDOCS3gog",
      "avatar_url": "https://avatars.githubusercontent.com/u/154001570?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Lavishgangwani",
      "html_url": "https://github.com/Lavishgangwani",
      "followers_url": "https://api.github.com/users/Lavishgangwani/followers",
      "following_url": "https://api.github.com/users/Lavishgangwani/following{/other_user}",
      "gists_url": "https://api.github.com/users/Lavishgangwani/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Lavishgangwani/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Lavishgangwani/subscriptions",
      "organizations_url": "https://api.github.com/users/Lavishgangwani/orgs",
      "repos_url": "https://api.github.com/users/Lavishgangwani/repos",
      "events_url": "https://api.github.com/users/Lavishgangwani/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Lavishgangwani/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-16T05:24:40Z",
    "updated_at": "2024-10-16T10:48:27Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60054",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60054",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60054.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60054.patch",
      "merged_at": null
    },
    "body": "### **Description:**\r\n\r\n#### **Overview**\r\nThis pull request addresses issue #59904, which involves a failure in date parsing within the `arrow_parser_wrapper` when reading CSV files using the PyArrow engine. The existing implementation encounters problems when processing missing values in the date column, resulting in the column being interpreted as a generic object type rather than a proper datetime type.\r\n\r\n#### **Issue Description**\r\nThe `read_csv` function in the `arrow_parser_wrapper` was failing to convert the date column to the expected `timestamp[ns][pyarrow]` dtype due to the presence of missing values. The absence of proper handling for these null entries led to the entire date column being inferred as an `object` dtype instead.\r\n\r\n#### **Modifications Made**\r\n1. **Enhanced Null Handling**: The code has been modified to incorporate checks for null values during the date parsing process. This ensures that missing entries are accounted for without causing a failure in type inference.\r\n   \r\n2. **Date Parsing Logic**: Adjustments have been made in the `read` method to validate and appropriately convert date columns. The modifications allow the function to return a DataFrame with the correct datetime dtype, even in the presence of missing values.\r\n\r\n3. **Testing**: A test case has been added to verify the expected behavior of date parsing when null values are included. This test checks that the date column is correctly interpreted as `timestamp[ns][pyarrow]`, regardless of any missing data.\r\n\r\n#### **Expected Behavior**\r\nWith these changes, users can expect the following improvements:\r\n- Date columns in CSV files will be accurately parsed to `timestamp[ns][pyarrow]`, ensuring consistent and expected behavior when handling time series data.\r\n- The presence of missing values will no longer disrupt the parsing process, allowing for more robust data ingestion workflows.\r\n\r\n#### **Conclusion**\r\nThis fix enhances the robustness of the date parsing functionality within the `arrow_parser_wrapper`, addressing the critical issue reported in #59904. The improvements not only solve the immediate problem but also provide a more reliable framework for handling CSV data with PyArrow in future applications.",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60054/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60054/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60053",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60053/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60053/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60053/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60053",
    "id": 2590380475,
    "node_id": "I_kwDOAA0YD86aZhG7",
    "number": 60053,
    "title": "BUG: numerical inconsistency in calculating rolling std, when the same data from different begining",
    "user": {
      "login": "tunkill",
      "id": 62743515,
      "node_id": "MDQ6VXNlcjYyNzQzNTE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/62743515?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tunkill",
      "html_url": "https://github.com/tunkill",
      "followers_url": "https://api.github.com/users/tunkill/followers",
      "following_url": "https://api.github.com/users/tunkill/following{/other_user}",
      "gists_url": "https://api.github.com/users/tunkill/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tunkill/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tunkill/subscriptions",
      "organizations_url": "https://api.github.com/users/tunkill/orgs",
      "repos_url": "https://api.github.com/users/tunkill/repos",
      "events_url": "https://api.github.com/users/tunkill/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tunkill/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 7,
    "created_at": "2024-10-16T02:05:01Z",
    "updated_at": "2024-10-18T09:08:10Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [ ] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\ntest = pd.read_csv('std_problem.csv', index_col=0, parse_dates=True)\r\n\r\nprint(test.rolling(1000).std().iloc[-1])\r\ndata    0.0\r\nName: 2018-01-03 08:45:00, dtype: float64\r\nprint(test.iloc[-35785:].rolling(1000).std().iloc[-1])\r\ndata    0.0\r\nName: 2018-01-03 08:45:00, dtype: float64\r\nprint(test.iloc[-35784:].rolling(1000).std().iloc[-1])\r\ndata    1.230596\r\nprint(test.iloc[-35781:].rolling(1000).std().iloc[-1])\r\ndata    0.959358\r\nName: 2018-01-03 08:45:00, dtype: float64\r\nName: 2018-01-03 08:45:00, dtype: float64\r\nprint(test.iloc[-1000:].rolling(1000).std().iloc[-1])\r\ndata    0.701844\r\nName: 2018-01-03 08:45:00, dtype: float64\r\nprint(np.std(test.iloc[-1000:], ddof=1))\r\ndata    0.701844\r\ndtype: float64\n```\n\n\n### Issue Description\n\nI have a data Series，which has a length of 93230，I want to calculate rolling std，but I got 0 for last one， that’s alomost impossible， so I check the result for only the last 1000 std， it’s the same with numpy.std, I found maybe from a special beging, the rolling std will give different results!\n\n### Expected Behavior\n\nI expect they give the same result: 0.701844,  no matter what the begining is, because the rolling 1000 should only use the latest 1000 numbers for the last std\r\n[std_problem.csv](https://github.com/user-attachments/files/17388072/std_problem.csv)\r\n\n\n### Installed Versions\n\n<details>\r\n\r\nI test with pandas = 2.1.2 and pandas = 2.2.3, both have the same problem\r\n\r\npd.show_versions()\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5\r\npython              : 3.10.13.final.0\r\npython-bits         : 64\r\nOS                  : Linux\r\nOS-release          : 6.8.0-45-generic\r\nVersion             : #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024\r\nmachine             : x86_64\r\nprocessor           : x86_64\r\nbyteorder           : little\r\nLC_ALL              : None\r\nLANG                : en_US.UTF-8\r\nLOCALE              : en_US.UTF-8\r\npandas              : 2.1.2\r\nnumpy               : 1.26.4\r\npytz                : 2024.1\r\ndateutil            : 2.9.0\r\nsetuptools          : 69.5.1\r\npip                 : 24.0\r\nlxml.etree          : 5.2.2\r\njinja2              : 3.1.4\r\nIPython             : 8.20.0\r\npandas_datareader   : 0.10.0\r\nbs4                 : 4.12.3\r\nbottleneck          : 1.3.7\r\nfsspec              : 2024.6.1\r\nmatplotlib          : 3.8.4\r\nnumba               : 0.59.1\r\nnumexpr             : 2.10.1\r\npyarrow             : 16.1.0\r\ns3fs                : 2024.6.1\r\nscipy               : 1.12.0\r\nsqlalchemy          : 2.0.31\r\ntables              : 3.9.2\r\ntabulate            : 0.9.0\r\nxarray              : 2024.6.0\r\nxlrd                : 2.0.1\r\nzstandard           : 0.22.0\r\ntzdata              : 2024.1\r\n\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\r\npython                : 3.11.10\r\npython-bits           : 64\r\nOS                    : Linux\r\nOS-release            : 6.8.0-45-generic\r\nVersion               : #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024\r\nmachine               : x86_64\r\nprocessor             : x86_64\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : en_US.UTF-8\r\nLOCALE                : en_US.UTF-8\r\n\r\npandas                : 2.2.3\r\nnumpy                 : 2.1.2\r\npytz                  : 2024.2\r\ndateutil              : 2.9.0.post0\r\npip                   : 24.2\r\nIPython               : 8.28.0\r\ntzdata                : 2024.2\r\n\r\n</details>\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60053/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60053/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60052",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60052/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60052/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60052/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60052",
    "id": 2589802207,
    "node_id": "PR_kwDOAA0YD85-ujdm",
    "number": 60052,
    "title": "Fix issue #59333",
    "user": {
      "login": "anzber",
      "id": 5594175,
      "node_id": "MDQ6VXNlcjU1OTQxNzU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5594175?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/anzber",
      "html_url": "https://github.com/anzber",
      "followers_url": "https://api.github.com/users/anzber/followers",
      "following_url": "https://api.github.com/users/anzber/following{/other_user}",
      "gists_url": "https://api.github.com/users/anzber/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/anzber/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/anzber/subscriptions",
      "organizations_url": "https://api.github.com/users/anzber/orgs",
      "repos_url": "https://api.github.com/users/anzber/repos",
      "events_url": "https://api.github.com/users/anzber/events{/privacy}",
      "received_events_url": "https://api.github.com/users/anzber/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-15T20:25:51Z",
    "updated_at": "2024-10-16T08:48:09Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60052",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60052",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60052.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60052.patch",
      "merged_at": null
    },
    "body": "- [x] closes #59933 \r\n- [x] Tests added and passed\r\n- [x] All code checks passed\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60052/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60052/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60051",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60051/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60051/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60051/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60051",
    "id": 2589240618,
    "node_id": "PR_kwDOAA0YD85-sxg8",
    "number": 60051,
    "title": "docs: add marimo to ecosystem.md",
    "user": {
      "login": "mscolnick",
      "id": 2753772,
      "node_id": "MDQ6VXNlcjI3NTM3NzI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2753772?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mscolnick",
      "html_url": "https://github.com/mscolnick",
      "followers_url": "https://api.github.com/users/mscolnick/followers",
      "following_url": "https://api.github.com/users/mscolnick/following{/other_user}",
      "gists_url": "https://api.github.com/users/mscolnick/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mscolnick/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mscolnick/subscriptions",
      "organizations_url": "https://api.github.com/users/mscolnick/orgs",
      "repos_url": "https://api.github.com/users/mscolnick/repos",
      "events_url": "https://api.github.com/users/mscolnick/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mscolnick/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-15T16:04:45Z",
    "updated_at": "2024-10-15T16:04:46Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60051",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60051",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60051.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60051.patch",
      "merged_at": null
    },
    "body": "We (https://github.com/marimo-team/marimo) have strong support for pandas, so was hoping to showcase that! Thank you for considering this PR\r\n\r\n- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60051/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60051/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60050",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60050/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60050/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60050/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60050",
    "id": 2588768619,
    "node_id": "I_kwDOAA0YD86aTXlr",
    "number": 60050,
    "title": "BUG: Creation of UInt64 column with `18446744073709551615` throws RuntimeWarning",
    "user": {
      "login": "Tishj",
      "id": 17162323,
      "node_id": "MDQ6VXNlcjE3MTYyMzIz",
      "avatar_url": "https://avatars.githubusercontent.com/u/17162323?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Tishj",
      "html_url": "https://github.com/Tishj",
      "followers_url": "https://api.github.com/users/Tishj/followers",
      "following_url": "https://api.github.com/users/Tishj/following{/other_user}",
      "gists_url": "https://api.github.com/users/Tishj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Tishj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Tishj/subscriptions",
      "organizations_url": "https://api.github.com/users/Tishj/orgs",
      "repos_url": "https://api.github.com/users/Tishj/repos",
      "events_url": "https://api.github.com/users/Tishj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Tishj/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-15T13:21:31Z",
    "updated_at": "2024-10-15T13:22:47Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport numpy.ma\r\nimport pandas\r\n\r\nprint(pandas.__version__)\r\n\r\ndata = {\r\n\t'a': numpy.ma.masked_array(\r\n\t\tmask=[\r\n\t\t\tTrue,\r\n\t\t\tTrue,\r\n\t\t\tFalse\r\n\t\t],\r\n\t\tdata=[\r\n\t\t\t0, 0, 18446744073709551615\r\n\t\t],\r\n\t\tdtype='uint64'\r\n\t)\r\n}\r\n\r\ndata['a'] = pandas.Series(data['a'], dtype='UInt64')\r\n\r\ndf = pandas.DataFrame.from_dict(data)\r\nprint(df['a'].dtype)\r\nprint(df)\r\n```\r\n\r\n```\r\n2.2.3\r\n/Users/thijs/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pandas/core/arrays/integer.py:55: RuntimeWarning: invalid value encountered in cast\r\n  casted = values.astype(dtype, copy=copy)\r\nUInt64\r\n                      a\r\n0                  <NA>\r\n1                  <NA>\r\n2  18446744073709551615\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nCreating a nullable uint64 column throws errors\r\n\r\n### Expected Behavior\r\n\r\nI would expect this to work without throwing an error, I don't get why the data is interpreted as a float64 when `uint64` is explicitly set as the dtype on the masked array\r\n\r\n### Installed Versions\r\n\r\n```\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\r\npython                : 3.11.0\r\npython-bits           : 64\r\nOS                    : Darwin\r\nOS-release            : 23.1.0\r\nVersion               : Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020\r\nmachine               : arm64\r\nprocessor             : arm\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : en_US.UTF-8\r\nLOCALE                : en_US.UTF-8\r\n\r\npandas                : 2.2.3\r\nnumpy                 : 1.26.4\r\npytz                  : 2024.1\r\ndateutil              : 2.8.2\r\npip                   : 24.0\r\nCython                : 3.0.11\r\nsphinx                : None\r\nIPython               : 8.22.0\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nblosc                 : None\r\nbottleneck            : None\r\ndataframe-api-compat  : None\r\nfastparquet           : None\r\nfsspec                : 2024.2.0\r\nhtml5lib              : None\r\nhypothesis            : None\r\ngcsfs                 : None\r\njinja2                : 3.1.3\r\nlxml.etree            : None\r\nmatplotlib            : None\r\nnumba                 : None\r\nnumexpr               : None\r\nodfpy                 : None\r\nopenpyxl              : None\r\npandas_gbq            : None\r\npsycopg2              : 2.9.9\r\npymysql               : None\r\npyarrow               : 17.0.0\r\npyreadstat            : None\r\npytest                : 8.0.0\r\npython-calamine       : None\r\npyxlsb                : None\r\ns3fs                  : None\r\nscipy                 : None\r\nsqlalchemy            : 2.0.35\r\ntables                : None\r\ntabulate              : None\r\nxarray                : None\r\nxlrd                  : None\r\nxlsxwriter            : None\r\nzstandard             : None\r\ntzdata                : 2023.4\r\nqtpy                  : None\r\npyqt5                 : None\r\n```",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60050/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60050/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60049",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60049/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60049/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60049/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60049",
    "id": 2588690267,
    "node_id": "I_kwDOAA0YD86aTEdb",
    "number": 60049,
    "title": "BUG: Boolean Series (actually object) with <NA> values breaks ~ negation and reverts to bit-wise operations",
    "user": {
      "login": "RedAero",
      "id": 43410273,
      "node_id": "MDQ6VXNlcjQzNDEwMjcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/43410273?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RedAero",
      "html_url": "https://github.com/RedAero",
      "followers_url": "https://api.github.com/users/RedAero/followers",
      "following_url": "https://api.github.com/users/RedAero/following{/other_user}",
      "gists_url": "https://api.github.com/users/RedAero/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RedAero/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RedAero/subscriptions",
      "organizations_url": "https://api.github.com/users/RedAero/orgs",
      "repos_url": "https://api.github.com/users/RedAero/repos",
      "events_url": "https://api.github.com/users/RedAero/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RedAero/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-15T12:51:41Z",
    "updated_at": "2024-10-15T12:56:37Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\n~pd.Series([True, False]) => [False, True]\r\n~pd.Series([True, False, pd.NA]) => [-2, -1, <NA>]\r\n\r\n~pd.Series([True, False, pd.NA], dtype=pd.BooleanDtype()) => [False, True, <NA>]\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nIn the example it is of course possible to work around the issue with forcing the dtype, but in the context of actual dataframes coming from real databases, NULLs are still best handled by simply replacing them with empty strings and hoping for the best, because no NULL-like object seems to work well with ordinary string and filter operations.\r\n\r\nAs a sidenote, if the pd.NA is instead a None, a TypeError is thrown.\r\n\r\n #59831 is a related issue. \r\n\r\n### Expected Behavior\r\n\r\nI'd expect the T/F values to flip and the NAs to remain by default, as they do when the dtype is forced.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140\r\npython                : 3.11.6.final.0\r\npython-bits           : 64\r\nOS                    : Windows\r\nOS-release            : 10\r\nVersion               : 10.0.19045\r\nmachine               : AMD64\r\nprocessor             : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : en\r\nLOCALE                : English_United Kingdom.1252\r\n\r\npandas                : 2.2.2\r\nnumpy                 : 1.26.4\r\npytz                  : 2023.3\r\ndateutil              : 2.8.2\r\nsetuptools            : 68.2.2\r\npip                   : 24.2\r\nCython                : 3.0.5\r\npytest                : 7.4.2\r\nhypothesis            : 6.87.1\r\nsphinx                : 6.1.3\r\nblosc                 : None\r\nfeather               : 0.4.1\r\nxlsxwriter            : 3.1.2\r\nlxml.etree            : 4.9.3\r\nhtml5lib              : 1.1\r\npymysql               : None\r\npsycopg2              : None\r\njinja2                : 3.1.2\r\nIPython               : 8.18.1\r\npandas_datareader     : None\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.2\r\nbottleneck            : 1.3.7\r\ndataframe-api-compat  : None\r\nfastparquet           : 2023.8.0\r\nfsspec                : 2023.9.2\r\ngcsfs                 : None\r\nmatplotlib            : 3.9.0\r\nnumba                 : 0.60.0\r\nnumexpr               : 2.8.7\r\nodfpy                 : None\r\nopenpyxl              : 3.1.2\r\npandas_gbq            : None\r\npyarrow               : 13.0.0\r\npyreadstat            : None\r\npython-calamine       : None\r\npyxlsb                : 1.0.10\r\ns3fs                  : None\r\nscipy                 : 1.14.0\r\nsqlalchemy            : 2.0.22\r\ntables                : 3.9.2\r\ntabulate              : 0.9.0\r\nxarray                : 2023.11.0\r\nxlrd                  : 2.0.1\r\nzstandard             : 0.22.0\r\ntzdata                : 2022.7\r\nqtpy                  : 2.4.1\r\npyqt5                 : None\r\n\r\n</details>\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60049/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60049/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60048",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60048/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60048/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60048/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60048",
    "id": 2588635997,
    "node_id": "I_kwDOAA0YD86aS3Nd",
    "number": 60048,
    "title": "ENH: Are there any possibility to add the support for static type hint of the DataFrame and Series ?",
    "user": {
      "login": "biosunsci",
      "id": 15091103,
      "node_id": "MDQ6VXNlcjE1MDkxMTAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/15091103?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/biosunsci",
      "html_url": "https://github.com/biosunsci",
      "followers_url": "https://api.github.com/users/biosunsci/followers",
      "following_url": "https://api.github.com/users/biosunsci/following{/other_user}",
      "gists_url": "https://api.github.com/users/biosunsci/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/biosunsci/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/biosunsci/subscriptions",
      "organizations_url": "https://api.github.com/users/biosunsci/orgs",
      "repos_url": "https://api.github.com/users/biosunsci/repos",
      "events_url": "https://api.github.com/users/biosunsci/events{/privacy}",
      "received_events_url": "https://api.github.com/users/biosunsci/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76812,
        "node_id": "MDU6TGFiZWw3NjgxMg==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement",
        "name": "Enhancement",
        "color": "4E9A06",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-15T12:29:00Z",
    "updated_at": "2024-10-15T12:29:00Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Feature Type\n\n- [X] Adding new functionality to pandas\n\n- [ ] Changing existing functionality in pandas\n\n- [ ] Removing existing functionality in pandas\n\n\n### Problem Description\n\n**New Feature Wanted**\r\n\r\n<!-- Enter a clear and concise description of your feature proposal here. -->\r\n\r\nWe Know that mypy and typing now support dict type hint by\r\n```python\r\nfrom typing import TypedDict, Optional, Literal\r\nclass OverlapsDict(TypedDict):\r\n    id: int\r\n    seq_id: int\r\n    pr_order: int\r\n    pos1: int\r\n    seq: str    \r\n    pos2: int\r\n    seq_len: int\r\n    repeat_info: float # exactly, should be np.nan\r\n    repeat_type: float # exactly, should be np.nan\r\n    item_type: Literal['overlap']\r\n    devmode: str\r\n    update_time: str\r\n```\r\nwe can use `OverlapsDict` to restrict dict parameters like \r\n\r\n```python\r\ndef myfunc(a:OverlapsDict):\r\n    pass\r\n```\r\n\r\n**Can the DataFrame and Series type also support a type hint like this, \r\nwhich will check that the `DataFrame.columns` or `Series.index` has the certain columns and their values are in certain dtypes.** \r\n\r\n\n\n### Feature Description\n\nis it possible to achieve a new type class `TypedDataFrame`  or make `DataFrame` or `Seires` Generic TypeVar which can be used as the following code?\r\n\r\n```python \r\n# define\r\nclass OverlapsDataFrame(TypedDataFrame):\r\n    id: int\r\n    seq_id: int\r\n    pr_order: int\r\n    pos1: int\r\n    seq: str    \r\n    pos2: int\r\n    seq_len: int\r\n    repeat_info: float # exactly, should be np.nan\r\n    repeat_type: float # exactly, should be np.nan\r\n    item_type: Literal['overlap']\r\n    devmode: str\r\n    update_time: str\r\n# usage\r\ndef myfunc2(a:OverlapsDataFrame):\r\n    pass\r\n```\r\nand / or \r\n```python\r\ndef myfunc2(a:pd.DataFrame[OverlapsDict]):\r\n    pass\r\n```\r\nAfter the definition, We can restrict DataFrame parameters with the `OverlapsDataFrame`. The constraint in the example is `a` must be a DataFrame and has columns of certain names with certain types defined by `OverlapsDataFrame` or\r\n`pd.DataFrame[OverlapsDict]`\r\n\r\n<!-- Please explain why this feature should be implemented and how it would be used. Add examples, if applicable. -->\n\n### Alternative Solutions\n\nIf both forms can be added is the best, either is OK.\r\n\n\n### Additional Context\n\n_No response_",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60048/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60048/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60047",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60047/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60047/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60047/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60047",
    "id": 2588590627,
    "node_id": "PR_kwDOAA0YD85-qqvk",
    "number": 60047,
    "title": "DOC: fix docstring of timedaltas.ceil",
    "user": {
      "login": "eightyseven",
      "id": 164823963,
      "node_id": "U_kgDOCdMDmw",
      "avatar_url": "https://avatars.githubusercontent.com/u/164823963?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eightyseven",
      "html_url": "https://github.com/eightyseven",
      "followers_url": "https://api.github.com/users/eightyseven/followers",
      "following_url": "https://api.github.com/users/eightyseven/following{/other_user}",
      "gists_url": "https://api.github.com/users/eightyseven/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eightyseven/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eightyseven/subscriptions",
      "organizations_url": "https://api.github.com/users/eightyseven/orgs",
      "repos_url": "https://api.github.com/users/eightyseven/repos",
      "events_url": "https://api.github.com/users/eightyseven/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eightyseven/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-10-15T12:09:05Z",
    "updated_at": "2024-10-15T13:01:43Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60047",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60047",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60047.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60047.patch",
      "merged_at": null
    },
    "body": "- [ ] closes #59902\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60047/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60047/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60046",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60046/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60046/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60046/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60046",
    "id": 2588426788,
    "node_id": "PR_kwDOAA0YD85-qJvX",
    "number": 60046,
    "title": "BUG: Fix copy semantics in ``__array__``",
    "user": {
      "login": "seberg",
      "id": 61977,
      "node_id": "MDQ6VXNlcjYxOTc3",
      "avatar_url": "https://avatars.githubusercontent.com/u/61977?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/seberg",
      "html_url": "https://github.com/seberg",
      "followers_url": "https://api.github.com/users/seberg/followers",
      "following_url": "https://api.github.com/users/seberg/following{/other_user}",
      "gists_url": "https://api.github.com/users/seberg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/seberg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/seberg/subscriptions",
      "organizations_url": "https://api.github.com/users/seberg/orgs",
      "repos_url": "https://api.github.com/users/seberg/repos",
      "events_url": "https://api.github.com/users/seberg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/seberg/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-15T11:06:31Z",
    "updated_at": "2024-10-15T13:02:22Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60046",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60046",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60046.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60046.patch",
      "merged_at": null
    },
    "body": "This should fix the semantics of ``__array__``.  While rejecting ``copy=False`` is OK even if unnecessary, ``copy=True`` should never have been ignored and is dangerous.\r\n\r\nCloses gh-57739, gh-59932\r\n\r\n- [ ] Still needs new tests.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n\r\n----\r\n\r\nI have to figure out the tests.  I think a test in form of:\r\n```\r\narr1 = np.asarray(obj, copy=True)\r\narr2 = np.asarray(obj, copy=True)\r\nassert not np.may_share_memory(arr1, arr2)\r\n# Check that without copy always works:\r\nassert_array_equal(arr1, np.asarray(obj))\r\n\r\nif np_ver < 2:\r\n    return  # copy=False semantics not supported\r\n\r\ntry:\r\n   arr1 = np.asarray(obj, copy=False)\r\nexcept ValueError:\r\n   return  # An error is acceptable for `copy=False`\r\n\r\n# If no error is given, multiple returns must be views:\r\narr2 = np.asarray(obj, copy=False)\r\nassert np.may_share_memory(arr1, arr2)\r\n```\r\nwill work nicely.  But, right now I am not sure if there is a convenient pattern/parametrization to steal to cover all of the `__array__` implementations here.",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60046/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60046/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60044",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60044/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60044/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60044/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60044",
    "id": 2587411029,
    "node_id": "I_kwDOAA0YD86aOMJV",
    "number": 60044,
    "title": "DOC: The `value` parameter of `pandas.Timedelta` can also accept float",
    "user": {
      "login": "5j9",
      "id": 1055747,
      "node_id": "MDQ6VXNlcjEwNTU3NDc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1055747?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/5j9",
      "html_url": "https://github.com/5j9",
      "followers_url": "https://api.github.com/users/5j9/followers",
      "following_url": "https://api.github.com/users/5j9/following{/other_user}",
      "gists_url": "https://api.github.com/users/5j9/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/5j9/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/5j9/subscriptions",
      "organizations_url": "https://api.github.com/users/5j9/orgs",
      "repos_url": "https://api.github.com/users/5j9/repos",
      "events_url": "https://api.github.com/users/5j9/events{/privacy}",
      "received_events_url": "https://api.github.com/users/5j9/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 134699,
        "node_id": "MDU6TGFiZWwxMzQ2OTk=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Docs",
        "name": "Docs",
        "color": "3465A4",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 5,
    "created_at": "2024-10-15T01:43:12Z",
    "updated_at": "2024-10-16T12:30:28Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)\r\n\r\n\r\n### Location of the documentation\r\n\r\nhttps://pandas.pydata.org/docs/dev/reference/api/pandas.Timedelta.html#pandas.Timedelta\r\n\r\n### Documentation problem\r\n\r\nIt currently states:\r\n\r\nhttps://github.com/pandas-dev/pandas/blob/2a10e04a099d5f1633abcdfbb2dd9fdf09142f8d/pandas/_libs/tslibs/timedeltas.pyx#L1867\r\n\r\nThere is no `float`.\r\n\r\n### Suggested fix for documentation\r\n\r\nAdd `float, ` to accepted types. \r\n\r\nThere already exists a code branch for `float` values so this should not be a problem:\r\nhttps://github.com/pandas-dev/pandas/blob/2a10e04a099d5f1633abcdfbb2dd9fdf09142f8d/pandas/_libs/tslibs/timedeltas.pyx#L2056",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60044/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60044/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60043",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60043/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60043/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60043/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60043",
    "id": 2587174566,
    "node_id": "PR_kwDOAA0YD85-mVq2",
    "number": 60043,
    "title": "Bugfix : Added `mathjax_ignore` to HTMLFormatter._write_table and changed tests to assert `mathjax_ignore`",
    "user": {
      "login": "Maru5er",
      "id": 74164821,
      "node_id": "MDQ6VXNlcjc0MTY0ODIx",
      "avatar_url": "https://avatars.githubusercontent.com/u/74164821?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Maru5er",
      "html_url": "https://github.com/Maru5er",
      "followers_url": "https://api.github.com/users/Maru5er/followers",
      "following_url": "https://api.github.com/users/Maru5er/following{/other_user}",
      "gists_url": "https://api.github.com/users/Maru5er/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Maru5er/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Maru5er/subscriptions",
      "organizations_url": "https://api.github.com/users/Maru5er/orgs",
      "repos_url": "https://api.github.com/users/Maru5er/repos",
      "events_url": "https://api.github.com/users/Maru5er/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Maru5er/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-10-14T22:19:47Z",
    "updated_at": "2024-10-15T17:42:45Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60043",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60043",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60043.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60043.patch",
      "merged_at": null
    },
    "body": "- [x] closes #59884 \r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n\r\nFeedback would be appreciated.",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60043/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60043/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60041",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60041/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60041/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60041/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60041",
    "id": 2586662360,
    "node_id": "I_kwDOAA0YD86aLVXY",
    "number": 60041,
    "title": "DOC: low Contrast issue",
    "user": {
      "login": "MR-Elbarbary",
      "id": 121816435,
      "node_id": "U_kgDOB0LFcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/121816435?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MR-Elbarbary",
      "html_url": "https://github.com/MR-Elbarbary",
      "followers_url": "https://api.github.com/users/MR-Elbarbary/followers",
      "following_url": "https://api.github.com/users/MR-Elbarbary/following{/other_user}",
      "gists_url": "https://api.github.com/users/MR-Elbarbary/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MR-Elbarbary/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MR-Elbarbary/subscriptions",
      "organizations_url": "https://api.github.com/users/MR-Elbarbary/orgs",
      "repos_url": "https://api.github.com/users/MR-Elbarbary/repos",
      "events_url": "https://api.github.com/users/MR-Elbarbary/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MR-Elbarbary/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 134699,
        "node_id": "MDU6TGFiZWwxMzQ2OTk=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Docs",
        "name": "Docs",
        "color": "3465A4",
        "default": false,
        "description": null
      },
      {
        "id": 40153326,
        "node_id": "MDU6TGFiZWw0MDE1MzMyNg==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Duplicate%20Report",
        "name": "Duplicate Report",
        "color": "009800",
        "default": false,
        "description": "Duplicate issue or pull request"
      },
      {
        "id": 2365504893,
        "node_id": "MDU6TGFiZWwyMzY1NTA0ODkz",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate",
        "name": "Closing Candidate",
        "color": "be21f2",
        "default": false,
        "description": "May be closeable, needs more eyeballs"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2024-10-14T17:39:09Z",
    "updated_at": "2024-10-15T10:32:54Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)\r\n\r\n\r\n### Location of the documentation\r\n\r\n[https://pandas.pydata.org/docs/getting_started/index.html#intro-to-pandas](url)\r\n\r\n### Documentation problem\r\n\r\nhere in dark mode,\r\nthe text has low contrast issue, it's hard to read the test\r\n![image](https://github.com/user-attachments/assets/59298eb6-5750-420a-9eab-fc47a7b8d75d)\r\n\r\n\r\n### Suggested fix for documentation\r\n\r\n```html\r\n<div class=\"d-flex flex-row tutorial-card-header-2\" bis_skin_checked=\"1\">\r\n<button class=\"btn btn-dark btn-sm\"></button>\r\nWhat kind of data does pandas handle?\r\n</div>\r\n```\r\nmaking the text color \"What kind of data does pandas handle\" white or any other bright color to increase the contrast\r\nmy changing the css color to white,\r\nIf you accept to fix this issue let me fix it (it will be my first PR)",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60041/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60041/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60040",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60040/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60040/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60040/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/60040",
    "id": 2586449484,
    "node_id": "PR_kwDOAA0YD85-kIPS",
    "number": 60040,
    "title": "DOC: fix docstring for DataFrame.round()",
    "user": {
      "login": "eightyseven",
      "id": 164823963,
      "node_id": "U_kgDOCdMDmw",
      "avatar_url": "https://avatars.githubusercontent.com/u/164823963?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eightyseven",
      "html_url": "https://github.com/eightyseven",
      "followers_url": "https://api.github.com/users/eightyseven/followers",
      "following_url": "https://api.github.com/users/eightyseven/following{/other_user}",
      "gists_url": "https://api.github.com/users/eightyseven/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eightyseven/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eightyseven/subscriptions",
      "organizations_url": "https://api.github.com/users/eightyseven/orgs",
      "repos_url": "https://api.github.com/users/eightyseven/repos",
      "events_url": "https://api.github.com/users/eightyseven/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eightyseven/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-10-14T15:54:22Z",
    "updated_at": "2024-10-15T13:04:49Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/60040",
      "html_url": "https://github.com/pandas-dev/pandas/pull/60040",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/60040.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/60040.patch",
      "merged_at": null
    },
    "body": "- [ ] #60009\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60040/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60040/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60039",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60039/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60039/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60039/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/60039",
    "id": 2586081852,
    "node_id": "I_kwDOAA0YD86aJHo8",
    "number": 60039,
    "title": "BUG: \"python make.py html\" for documentation is giving error",
    "user": {
      "login": "Swati-Sneha",
      "id": 16612983,
      "node_id": "MDQ6VXNlcjE2NjEyOTgz",
      "avatar_url": "https://avatars.githubusercontent.com/u/16612983?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Swati-Sneha",
      "html_url": "https://github.com/Swati-Sneha",
      "followers_url": "https://api.github.com/users/Swati-Sneha/followers",
      "following_url": "https://api.github.com/users/Swati-Sneha/following{/other_user}",
      "gists_url": "https://api.github.com/users/Swati-Sneha/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Swati-Sneha/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Swati-Sneha/subscriptions",
      "organizations_url": "https://api.github.com/users/Swati-Sneha/orgs",
      "repos_url": "https://api.github.com/users/Swati-Sneha/repos",
      "events_url": "https://api.github.com/users/Swati-Sneha/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Swati-Sneha/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2024-10-14T13:38:44Z",
    "updated_at": "2024-10-15T04:58:01Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\npython make.py html\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nWhile trying to [build documentation](https://pandas.pydata.org/docs/dev/development/contributing_documentation.html#building-the-documentation) for pandas-dev, the build fails with **Sphinx parallel build error**\r\n<img width=\"1071\" alt=\"Screenshot 2024-10-14 at 19 06 45\" src=\"https://github.com/user-attachments/assets/9c1c2fc7-c313-43a3-a65d-f18f4099cba4\">\r\n\r\n\r\n[Stackoverflow Issue Reference](https://stackoverflow.com/questions/79062269/pandas-dev-local-setup-is-failing-when-building-documentation)\r\n\r\n\r\n\r\n### Expected Behavior\r\n\r\nThe build should be successful and the docs should be built in local\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : 2a10e04a099d5f1633abcdfbb2dd9fdf09142f8d\r\npython                : 3.10.15\r\npython-bits           : 64\r\nOS                    : Darwin\r\nOS-release            : 23.6.0\r\nVersion               : Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:39 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T8122\r\nmachine               : arm64\r\nprocessor             : arm\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : en_US.UTF-8\r\nLOCALE                : en_US.UTF-8\r\n\r\npandas                : 0+untagged.35606.g2a10e04\r\nnumpy                 : 1.26.4\r\ndateutil              : 2.9.0\r\npip                   : 24.2\r\nCython                : 3.0.11\r\nsphinx                : 8.1.1\r\nIPython               : 8.28.0\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nblosc                 : None\r\nbottleneck            : 1.4.0\r\nfastparquet           : 2024.5.0\r\nfsspec                : 2024.9.0\r\nhtml5lib              : 1.1\r\nhypothesis            : 6.114.1\r\ngcsfs                 : 2024.9.0post1\r\njinja2                : 3.1.4\r\nlxml.etree            : 5.3.0\r\nmatplotlib            : 3.9.2\r\nnumba                 : 0.60.0\r\nnumexpr               : 2.10.1\r\nodfpy                 : None\r\nopenpyxl              : 3.1.5\r\npsycopg2              : 2.9.9\r\npymysql               : 1.4.6\r\npyarrow               : 17.0.0\r\npyreadstat            : 1.2.7\r\npytest                : 8.3.3\r\npython-calamine       : None\r\npytz                  : 2024.2\r\npyxlsb                : 1.0.10\r\ns3fs                  : 2024.9.0\r\nscipy                 : 1.14.1\r\nsqlalchemy            : 2.0.35\r\ntables                : 3.10.1\r\ntabulate              : 0.9.0\r\nxarray                : 2024.9.0\r\nxlrd                  : 2.0.1\r\nxlsxwriter            : 3.2.0\r\nzstandard             : 0.23.0\r\ntzdata                : 2024.2\r\nqtpy                  : None\r\npyqt5                 : None\r\n\r\n</details>\r\n",
    "closed_by": null,
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/60039/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/60039/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  }
]
